### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by uwkoichi** [uwkoichi/chat-space#11]
# IPアドレス
18.180.27.213

**Comment by chiii220** [comment]
赤間さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
○画面のビュー崩れ（editボタンやsendボタンが見えない）
<img width="1440" alt="スクリーンショット 2020-03-27 10 04 29" src="https://user-images.githubusercontent.com/55054853/77710984-09d70f00-7013-11ea-883a-bb7912b8068c.png">



○グループ名とグループ名の間の余白が狭い
仕様書を参考にされてください。
<img width="302" alt="スクリーンショット 2020-03-27 10 08 05" src="https://user-images.githubusercontent.com/55054853/77710980-05125b00-7013-11ea-85bd-140298f68186.png">

※カリキュラムの中にある、模範のchatspaceと仕様書を参考に、修正をお願いします。
[模範のchatpsace]
https://chat-space-sample.herokuapp.com/
[仕様書]
https://tech-master.s3.amazonaws.com/uploads/curriculums//03e925297f3843c603f028b177b4e86b.png

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by uwkoichi** [comment]
修正しました

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
